#include<iostream.h>
#include<conio.h>
#include<stdio.h>
#include<string.h>
#include<ctype.h>
#include<stdlib.h>
#include<time.h>
int b=0;

void qt1()
{
char a;
cout<<endl<<endl<<"what is the square root of 2 ? ";
cout<<endl<<"A. 1                      B. 2 ";
cout<<endl<<"C. 1.5                    D. 1.4 "<<endl;
cin>>a;
clrscr();
if(a=='a'||a=='A')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt2()
{
char a;
cout<<endl<<"what is the dimmension of velocity ";
cout<<endl<<"A. MLT                  B. LT-2";
cout<<endl<<"C. LT-1                 D. MT-1"<<endl;
cin>>a;
clrscr();
if(a=='c'||a=='C')
{
cout<<endl<<"Correct Answer";
::b++;}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt3()
{
char a;
cout<<endl<<"what is the capital of india ? ";
cout<<endl<<"A. delhi             B.mumbai ";
cout<<endl<<"C. culcuta           D. jaipur "<<endl;
cin>>a;
clrscr();
if(a=='a'||a=='A')
{
cout<<endl<<"Correct Answer";
::b++;}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt4()
{
char a;
cout<<endl<<"what is the si unit of force ";
cout<<endl<<"A. N                  B. Ns" ;
cout<<endl<<"C. Kg/m               D. kg/sec "<<endl;
cin>>a;
clrscr();
if(a=='a'||a=='A')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt5()
{
char a;
cout<<endl<<"value assigned to _______can be changed  ";
cout<<endl<<" A.variables          B.data";
cout<<endl<<" C.constant           D.program  "<<endl;
cin>>a;
clrscr();
if(a=='a'||a=='A')
{
::b++;
cout<<endl<<"Correct Answer";
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt6()
{
char a;
cout<<endl<<"1 byte = _______bits ";
cout<<endl<<" A.2                 B.4";
cout<<endl<<" C.6                 D.8"<<endl;
cin>>a;
clrscr();
if(a=='d'||a=='D')
{
::b++;
cout<<endl<<"Correct Answer";
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt7()
{
char a;
cout<<endl<<"in if statment ,condition is always written in ?";
cout<<endl<<"A.[]                  B.{}";
cout<<endl<<"C.()                  D.<>"<<endl;
cin>>a;
clrscr();
if(a=='c'||a=='C')
{
::b++;
cout<<endl<<"Correct Answer";
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt8()
{
char a;
cout<<endl<<"In a compound statment ,one or more statment are closed in ?";
cout<<endl<<"A.()                   B.{}";
cout<<endl<<"C.<>                   D.[]"<<endl;
cin>>a;
clrscr();
if(a=='a'||a=='A')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt9()
{
char a;
cout<<endl<<"which statment stores input values ";
cout<<endl<<"A. main()              B.void()";
cout<<endl<<"C.clrscr()             D.cin>>"<<endl;
cin>>a;
clrscr();
if(a=='d'||a=='D')
{
::b++;
cout<<endl<<"Correct Answer";
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt10()
{
char a;
cout<<endl<<"each  switch case block ends with ______";
cout<<endl<<"A. endl;           B. next;";
cout<<endl<<"C.break;           D. exit();"<<endl;
cin>>a;
clrscr();
if(a=='c'||a=='C')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt11()
{
char a;
cout<<endl<<"in switch _______&________are optional ";
cout<<endl<<"A.case,break          B. break,default";
cout<<endl<<"C.switch,break        D. case,switch"<<endl;
cin>>a;
clrscr();
if(a=='b'||a=='B')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt12()
{
char a;
cout<<endl<<"an if statment used with another if called ?";
cout<<endl<<"A.simple if       B.nested if ";
cout<<endl<<"C. if else        D. switch "<<endl;
cin>>a;
clrscr();
if(a=='B'||a=='b')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt13()
{
char a;
cout<<endl<<"the binary of digit 13 is ";
cout<<endl<<"A. 1101        B.1110";
cout<<endl<<"C. 1111        D. 10001"<<endl;
cin>>a;
clrscr();
if(a=='a'||a=='A')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt14()
{
char a;
cout<<endl<<"using binary code what will be the sum of the digit 0110 &0101";
cout<<endl<<"A. 0211            B.0111";
cout<<endl<<"C.1011             D. 110101"<<endl;
cin>>a;
clrscr();
if(a=='c'||a=='C')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt15()
{
char a;
cout<<endl<<"whch of these is syntactically incorrect ";
cout<<endl<<"A. x+y=4               B. x=x+1;";
cout<<endl<<"C. x+=y+z              D. y++ + +z"<<endl;
cin>>a;
clrscr();
if(a=='d'||a=='D')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt16()
{
char a;
cout<<endl<<"which of these is a increment opreator ?";
cout<<endl<<"A. +          B. ++";
cout<<endl<<"C. ++         D.  --"<<endl;
cin>>a;
clrscr();
if(a=='c'||a=='C')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt17()
{
char a;
cout<<endl<<"logical _____ is used when the condition must be satisfied ";
cout<<endl<<"A. OR                B.AND ";
cout<<endl<<"C.BUT               D. NOT "<<endl;
cin>>a;
clrscr();
if(a=='B'||a=='b')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt18()
{
char a;
cout<<endl<<"which operator is used as logical OR ";
cout<<endl<<"A. &         B. &&";
cout<<endl<<"C. ||        D. | "<<endl;
cin>>a;
clrscr();
if(a=='c'||a=='C')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt19()
{
char a;
cout<<endl<<"the header of the statment contains 3 expessions in the parntheses ";
cout<<endl<<"A. while               B. do ";
cout<<endl<<"C. for                D.  do-while "<<endl;
cin>>a;
clrscr();
if(a=='c'||a=='C')
{
cout<<endl<<"Correct Answer";
::b++;
}
else
cout<<endl<<" Wrong Answer ";getch();
}
void qt20()
{
char a;
cout<<endl<<"which loop is used when number of itretaions are not known ?";
cout<<endl<<"A. for             B.while ";
cout<<endl<<"C. do-while        D. do  "<<endl;
cin>>a;
cout<<endl<<endl;
if(a=='b'||a=='B')
{
cout<<endl<<"Correct Answer ";
::b++;
}
else
cout<<endl<<" Wrong Answer ";
getch();
}

struct cnst
{ int age,clas,roll;
  char name[25];
};

void main()
{
clrscr();
cnst cont;
int a,b,c,d,i,j;
cout<<endl<<"\tEnter ur details "<<endl;
cout<<endl<<"\tEnter ur name     : ";
cin>>cont.name;
cout<<endl<<"\tEnter ur age      : ";
cin>>cont.age;
cout<<endl<<"\tEnter ur class    : ";
cin>>cont.clas;
cout<<endl<<"\tEnter ur roll no. : ";
cin>>cont.roll;
for(i=0;i<5;i++)
{
clrscr();
cout<<endl<<"\t\tQuestion no. : "<<i+1<<endl<<endl;
randomize();
a=(random (20)+1);
switch(a)
{
  case 1:qt1();
   break;
  case 2:qt2();
   break;
  case 3:qt3();
   break;
  case 4:qt4();
   break;
  case 5:qt5();
   break;
  case 6:qt6();
   break;
  case 7:qt7();
   break;
  case 8:qt8();
   break;
  case 9:qt9();
   break;
  case 10:qt10();
   break;
  case 11:qt11();
   break;
  case 12:qt12();
   break;
  case 13:qt13();
   break;
  case 14:qt14();
   break;
  case 15:qt15();
   break;
  case 16:qt16();
   break;
  case 17:qt17();
   break;
  case 18:qt18();
   break;
  case 19:qt19();
   break;
  case 20:qt20();
   break;
   }
}

clrscr();
cout<<endl<<"NAME:"<<cont.name<<endl<<"\tCLASS"<<cont.clas<<endl<<"\t\tROLL NO."<<cont.roll;
cout<<endl<<endl<<"\tYour score card shows  : "<<::b<<" marks which means urperformance was ";
switch(::b)
{
case 1:cout<<endl<<"\t\tpoor in the game ";
break;
case 2:cout<<endl<<"\t\taverage in the game";
break;
case 3:cout<<endl<<"\t\tgood in the game ";
break;
case 4:cout<<endl<<"\t\tvery good in the game ";
break;
case 5:cout<<endl<<"\t\tsuperb in the game ....";
break;
default :cout<<endl<<"\t\tbad in the game, better luck next time ";
}


cout<<endl;
getch();
getch();
}


