// the program for showing the working of simple if-else

#include <iostream.h>
#include<conio.h>
void main ()
{
clrscr();
int number=33;

// if condition
if(number<30)
 {
 //if the condition is satisfied
 cout<<endl<<"number is less than 20";
 }

else
 {
 //if the condition is not satisfied
 cout<<endl<<"number is not less than 20";
 }

cout<<endl<< "value of number is : "<<number;
getch();
}